import { FiArrowRight, FiMinus, FiPlus, FiShoppingBag, FiTrash2, FiX } from 'react-icons/fi'

function CartPanel({ cart, onClose, onChangeQuantity, onRemove }) {
  const subtotal = cart.reduce((total, item) => total + item.price * item.quantity, 0)
  const fallbackImage = 'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?auto=format&fit=crop&w=700&q=85'
  const handleImageError = (event) => { if (event.currentTarget.src !== fallbackImage) event.currentTarget.src = fallbackImage }
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><aside className="cart-panel" role="dialog" aria-modal="true" aria-labelledby="cart-title"><div className="panel-heading"><h2 id="cart-title">Your bag <span>({cart.reduce((total, item) => total + item.quantity, 0)})</span></h2><button className="modal-close" onClick={onClose} aria-label="Close shopping cart"><FiX /></button></div>{cart.length ? <><div className="cart-list">{cart.map((item) => <div className="cart-item" key={item.id}><div className="cart-thumb"><img src={item.image} alt={item.name} onError={handleImageError} /></div><div className="cart-item-copy"><span className="product-brand">Glowify</span><h3>{item.name}</h3><strong>₹{item.price.toLocaleString('en-IN')}</strong><div className="cart-quantity"><button onClick={() => onChangeQuantity(item.id, -1)} aria-label={`Decrease ${item.name} quantity`}><FiMinus /></button><span>{item.quantity}</span><button onClick={() => onChangeQuantity(item.id, 1)} aria-label={`Increase ${item.name} quantity`}><FiPlus /></button></div></div><button className="remove-cart" onClick={() => onRemove(item.id)} aria-label={`Remove ${item.name} from cart`}><FiTrash2 /></button></div>)}</div><div className="cart-summary"><div><span>Subtotal</span><strong>₹{subtotal.toLocaleString('en-IN')}</strong></div><p>Shipping and taxes calculated at checkout.</p><button className="primary-button checkout-button" onClick={onClose}>Checkout <FiArrowRight /></button></div></> : <div className="empty-wishlist cart-empty"><FiShoppingBag /><h3>Your bag is empty</h3><p>Add a product and it will appear here.</p><button className="primary-button" onClick={onClose}>Continue shopping <FiArrowRight /></button></div>}</aside></div>
}

export default CartPanel
