import { useState } from 'react'
import { FiCheck, FiFacebook, FiInstagram, FiMail, FiMapPin, FiYoutube, FiX } from 'react-icons/fi'
import { Logo } from './Navbar'

function Footer() {
  const [subscribed, setSubscribed] = useState(false)
  const [legalPage, setLegalPage] = useState(null)
  const subscribe = (event) => { event.preventDefault(); setSubscribed(true); event.currentTarget.reset() }
  return <><footer className="footer"><div className="footer-main"><div className="footer-brand"><Logo /><p>Skincare for a brighter you.</p><div className="socials"><a href="https://www.instagram.com/" target="_blank" rel="noreferrer" aria-label="Instagram"><FiInstagram /></a><a href="https://www.facebook.com/" target="_blank" rel="noreferrer" aria-label="Facebook"><FiFacebook /></a><a href="https://www.youtube.com/" target="_blank" rel="noreferrer" aria-label="YouTube"><FiYoutube /></a><a href="https://www.pinterest.com/" target="_blank" rel="noreferrer" aria-label="Pinterest"><FiMapPin /></a></div></div><div className="footer-column"><h4>Quick links</h4><a href="#top">Home</a><a href="#shop">Shop</a><a href="#about">About</a><a href="#contact">Contact</a></div><div className="footer-column"><h4>Customer support</h4><a href="#contact">FAQs</a><a href="#contact">Shipping & delivery</a><a href="#contact">Returns & refunds</a><a href="#contact">Track order</a></div><div className="newsletter"><h4>Stay in the glow</h4><p>Join our list for rituals, tips and a little joy.</p>{subscribed ? <p className="newsletter-success"><FiCheck /> You are on the list.</p> : <form onSubmit={subscribe}><label><FiMail /><input required placeholder="Your email address" type="email" aria-label="Newsletter email" /><button type="submit">Subscribe</button></label></form>}</div></div><div className="footer-bottom"><span>© 2024 Glowify. All rights reserved.</span><div><button className="legal-link" onClick={() => setLegalPage('privacy')}>Privacy policy</button><button className="legal-link" onClick={() => setLegalPage('terms')}>Terms & conditions</button></div></div></footer>{legalPage && <div className="legal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setLegalPage(null)}><section className="legal-modal" role="dialog" aria-modal="true" aria-labelledby="legal-title"><button className="modal-close" onClick={() => setLegalPage(null)} aria-label="Close legal page"><FiX /></button><p className="eyebrow">Glowify</p><h2 id="legal-title">{legalPage === 'privacy' ? 'Privacy policy' : 'Terms & conditions'}</h2><p>{legalPage === 'privacy' ? 'We use your information only to improve your Glowify experience, process orders and respond to support requests. We do not sell personal information.' : 'Glowify products, content and this website are provided for personal use. Prices, availability and product details may change as we improve our collection.'}</p><p>For questions, contact us at <a href="mailto:hello@glowify.in">hello@glowify.in</a>.</p></section></div>}</>
}

export default Footer
